company.collect:
  path: /
  controller: App\Company\Controller\CompanyController::collect
  methods: GET
company.create:
  path: /
  controller: App\Company\Controller\CompanyController::create
  methods: POST
company.update:
  path: /{companyId}
  controller: App\Company\Controller\CompanyController::update
  methods: PUT
  requirements:
    companyId: '\d+'
company.delete:
  path: /{companyId}
  controller: App\Company\Controller\CompanyController::delete
  methods: DELETE
  requirements:
    companyId: '\d+'
company.get:
  path: /{companyId}
  controller: App\Company\Controller\CompanyController::get
  methods: GET
  requirements:
    companyId: '\d+'