nelmio_api_doc:
    documentation:
        info:
            title: CRUD API
            description: Symfony
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!api/doc$|_error).*$
