services:
  php:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
